version: "3.8"

services:
  web:
    build: .
    command: python ./src/main.py
    ports:
      - "16200:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      DB_URL: ${DB_URL}

  redis:
    image: redis:latest
    ports:
      - "6379:6379"